services:
  librechat_api:
    image: ghcr.io/gradient-ds/librechat-api:${LIBRECHAT_TAG:-latest}
    container_name: librechat_api
    restart: unless-stopped
    labels:
      - "govgpt.restart=enabled"
    environment:
      CONFIG_PATH: /app/librechat.merged.yaml
      BASE_CONFIG_PATH: /app/librechat.yaml
      HOST: 0.0.0.0
      PORT: 3080
      MONGO_URI: mongodb://mongodb:27017/LibreChat
      MEILI_HOST: http://meilisearch:7700
      RAG_API_URL: http://rag_api:8000
      GOVGPT_ROOT: /app
    depends_on:
      - mongodb
      - rag_api
    env_file:
      - .env
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
      - ./librechat.merged.yaml:/app/librechat.merged.yaml:rw
      - ./admin-overrides.yaml:/app/admin-overrides.yaml:rw
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
    ports:
      - "3080:3080"

  mongodb:
    image: mongo
    container_name: prod-mongodb
    restart: unless-stopped
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth

  meilisearch:
    image: getmeili/meilisearch:v1.12.3
    container_name: prod-meilisearch
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.12:/meili_data

  vectordb:
    image: ankane/pgvector:latest
    container_name: prod-vectordb
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    container_name: prod-rag-api
    restart: unless-stopped
    depends_on:
      - vectordb
    environment:
      DB_HOST: vectordb
      RAG_PORT: 8000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    env_file:
      - .env


volumes:
  pgdata2: