services:
  mongodb:
    image: mongo
    container_name: dev-mongodb
    restart: unless-stopped
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
    ports:
      - "27017:27017"

  meilisearch:
    image: getmeili/meilisearch:v1.12.3
    container_name: dev-meilisearch
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data_v1.12:/meili_data
    ports:
      - "7700:7700"

  vectordb:
    image: ankane/pgvector:latest
    container_name: dev-vectordb
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    container_name: dev-rag-api
    restart: unless-stopped
    depends_on:
      - vectordb
    environment:
      DB_HOST: vectordb
      RAG_PORT: 8000
      OLLAMA_HOST: http://ollama:11434
    env_file:
      - .env
    ports:
      - "8000:8000"
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama        # models are cached here
    environment:
      - OLLAMA_DISABLE_TELEMETRY=1
volumes:
  pgdata2: 
  ollama: